server:
  port: 9001
spring:
  application:
     name: AIGOU_ZUUL #不要使用下划线
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/ #告诉服务提供者要把服务注册到哪儿
  instance:
    prefer-ip-address: true

zuul:
  routes:
    aigou_plat: /login/** #以/user开头的所有路径都转发给USER-CONSUMER进行处理
  ignored-services: "*" #忽略掉服务名访问方式 使用上面/user的方式来访问
  prefix: /aigou