server:
  port: 8001
spring:
  application:
     name: AIGOU_PLAT #不要使用下划线
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/ #告诉服务提供者要把服务注册到哪儿
  instance:
    prefer-ip-address: true