server:
  port: 8848
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/
  instance:
    prefer-ip-address: true
spring:
  application:
    name: AIGOU_CONFIG_SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yaoniang/aigou_config.git
          username: yaoniang
          password: xy514523