server:
  port: 7001
eureka:
  instance:
    hostname: eureka
  client:
      registerWithEureka: false #是否要注册到eureka
      fetchRegistry: false #表示是否从Eureka Server获取注册信息
      serviceUrl:
        defaultZone: http://127.0.0.1:7001/eureka/
spring:
  application:
    name: AIGOU_EUREKA